### ISSUE TITLE
config_declaration.yaml missing from pip package

### ISSUE THREAD

**Issue by canon-cmre-kym-eden** [DataShades/ckanext-ingest#1]
CKAN 2.10 expects _config_declaration_ file but this isn't in the package installed by `pip install ckanext-ingest`.  Workaround for now is to install the git repo instead.

**Comment by smotornyuk** [comment]
Thank you for the report. 
Issue fixed in [v1.4.2](https://pypi.org/project/ckanext-ingest/)

**Comment by canon-cmre-kym-eden** [comment]
You're welcome.  Thanks for getting it pushed out quickly.
